name: Publish flow

on: 
  release:
    types:
      - published

jobs:
  build:
    runs_on: ubuntu_latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build --if-present
      - uses: jgierer12/npm-auth-gpr@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Pre-Release version
        if: "github.event.release.prerelease"
        run: npm publish --tag beta
      - name: Publish Latest version
        if: "!github.event.release.prerelease"
        run: npm publish
